# useful autocorrect rules
#whitelist_rules:
#   - vertical_whitespace_closing_braces
#   - vertical_whitespace_between_cases
#   - return_arrow_whitespace
#   - redundant_void_return
#   - redundant_type_annotation
#   - redundant_nil_coalescing
#   - prefer_self_type_over_type_of_self
#   - literal_expression_end_indentation
#   - leading_whitespace
#   - empty_parentheses_with_trailing_closure
#   - empty_enum_arguments
#   - anyobject_protocol
#   - unneeded_parentheses_in_closure_argument
#   - void_return
#   - colon

disabled_rules:
    - trailing_comma
#   - function_parameter_count
    - line_length
#   - file_length
#   - function_body_length
    - identifier_name
#   - force_cast
#   - nesting

    # temporary disable
#   - vertical_whitespace_between_cases
#   - statement_position
#   - private_outlet
#   - private_action
#   - attributes
#   - force_unwrapping
#   - implicitly_unwrapped_optional
#   - cyclomatic_complexity
#   - convenience_type
#   - orphaned_doc_comment
#   - multiline_arguments
#   - multiline_function_chains
#   - for_where
#   - discouraged_optional_boolean
#   - discouraged_optional_collection
#   - todo
#   - empty_count
#   - weak_delegate
#   - unused_optional_binding
#    - strict_fileprivate
#    - strong_iboutlet
#    - trailing_closure
#    - conditional_returns_on_newline
#    - unneeded_break_in_switch
#    - yoda_condition
#    - notification_center_detachment
#    - sorted_first_last
#    - vertical_parameter_alignment_on_call
#    - shorthand_operator
#    - valid_ibinspectable
#    - implicit_getter
#    - operator_whitespace
#    - switch_case_alignment
#    - force_try
#    - closure_body_length
#    - let_var_whitespace
#    - pattern_matching_keywords
#    - legacy_hashing
#    - function_default_parameter_at_end
#    - discarded_notification_center_observer
#    - contains_over_filter_is_empty
#    - prefixed_toplevel_constant
#    - empty_xctest_method
#    - collection_alignment
#    - redundant_string_enum_value
#    - overridden_super_call
#    - unavailable_function
#    - class_delegate_protocol
#    - first_where
#    - vertical_parameter_alignment
#    - multiple_closures_with_trailing_closure
#    - override_in_extension
#    - empty_string
#    - type_name
#    - colon
#    - switch_case_on_newline
#    - unused_closure_parameter
#    - closure_parameter_position
#    - fatal_error_message
#    - generic_type_name
#    - unowned_variable_capture
#    - block_based_kvo
#    - legacy_multiple
#    - contains_over_first_not_nil
#    - unused_setter_value
#    - reduce_into
#    - unused_capture_list
#    - legacy_random
#    - static_operator
#    - array_init
#    - xct_specific_matcher
#    - explicit_init

opt_in_rules: # some rules are only opt-in
    - anyobject_protocol
    - array_init
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
#    - enum_case_associated_values_count
    - explicit_init
    - expiring_todo
#    - explicit_acl
#    - explicit_enum_raw_value
    - explicit_self
#    - explicit_top_level_acl
#    - explicit_type_interface
#    - extension_access_modifier
    - fallthrough
    - fatal_error_message
#    - file_header
    - file_length
#    - file_name
    - file_name_no_space
#    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_body_length
    - function_default_parameter_at_end
    - function_parameter_count
    - identical_operands
#    - implicit_return
    - implicitly_unwrapped_optional
#    - indentation_width
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_random
    - let_var_whitespace
    - line_length
    - literal_expression_end_indentation
#    - lower_acl_than_parent
#    - missing_docs
    - modifier_order
    - multiline_arguments
#    - multiline_arguments_brackets
    - multiline_function_chains
#    - multiline_literal_brackets
#    - multiline_parameters
#    - multiline_parameters_brackets
    - nimble_operator
#    - no_extension_access_modifier
#    - no_grouping_extension
#    - nslocalizedstring_key
#    - nslocalizedstring_require_bundle
#    - number_separator
#    - object_literal
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
#    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - raw_value_for_camel_cased_codable_enum
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
#    - required_deinit
    - required_enum_case
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - strong_iboutlet
    - switch_case_on_newline
    - toggle_bool
    - trailing_closure
    - trailing_comma
#    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_opening_braces
    - vertical_whitespace_closing_braces
    - vertical_whitespace_between_cases
    - xct_specific_matcher
    - yoda_condition

    # Find all the available rules by running:
    # swiftlint rules

excluded:
    - Pods

statement_position:
    statement_mode: uncuddled_else

